### PR TITLE
Fixed bug with non-present style

### PR DESCRIPTION
**Pull request by basvdheijden**

### CODE REVIEW

**Comment by mwilliamson** [comment]
Thanks for the pull request. I'd be curious to know under what conditions this happens: is the document actually referencing a missing style, or is Mammoth failing to find the style?

In either case, it feels like a warning should be emitted. Also, would you mind covering any changes with tests?

**Comment by basvdheijden** [comment]
Sorry, as I'm really busy currently I do not have the time to write test coverage. I could send you the document over mail where this happened if you'd like to have a working copy of the bug?

**Comment by mwilliamson** [comment]
> I could send you the document over mail where this happened if you'd like to have a working copy of the bug?

Please do!

**Comment by mwilliamson** [comment]
Closing since this is now fixed in `master`, but if you have a moment to send over the example document, that would be great!

**Pull request closed without merging**
