### PR TITLE
styles names should be null by default

### PR DESCRIPTION
**Pull request by jaceyshome**
The style name can be undefined, so set it to null by default.

### CODE REVIEW

**Comment by mwilliamson** [comment]
Thanks for the pull request! Couple of comments:

* The convention in this project is four spaces for indentation. Would you mind changing your additions for consistency?

* Without the changes to the code under test, do the tests you've written fail? It seems to me that the tests set the `w:val` attribute to null, whereas the code under test is handling a different case, namely when the `w:name` element doesn't exist.

**Comment by jaceyshome** [comment]
Thanks for your comments.

Yes, I should make the indentation for four spaces. About the test case, I did it wrong. It should test the condition when a style doesn't contain w:name element. 

I changed the indent to 4 spaces and updated the test case.  Also I created a function 'styleWithoutWNameElement', I don't think the function name is good, but feel free to suggest a better name.

**Comment by mwilliamson** [comment]
Looks pretty good to me. Just one question: is it necessary to create `new XmlElement("w:notName", {"w:val": name}, [])`? In other words, in the test itself, why not just say `styleWithoutWNameElement("paragraph", "Heading1")`?

**Comment by jaceyshome** [comment]
Good idea, it is unnecessary to create an element 'w:notName'. I removed it. Thanks.

**Comment by mwilliamson** [comment]
I've just published 0.3.20 to npm, which includes this change. Thanks!

**Comment by jaceyshome** [comment]
It is my pleasure ;). Thank you for this awesome mammoth.js.

**Pull request merged**
