### PR TITLE
Handle highlight

### PR DESCRIPTION
**Pull request by iGitScor**
Handle highlighted text and map it to mark markup

### CODE REVIEW

**Comment by mwilliamson** [comment]
This seems to convert all shadow and highlight elements to overline: isn't that going to capture many cases that aren't overline?

**Comment by iGitScor** [comment]
Hello @mwilliamson, sorry for the late answer. It will ensure compatibility with new (highlight) and previous (shadow) word version to mark them as highlighted text

**Comment by VictorBaron** [comment]
This would definitely be a blast to have this feature 😁 
If I can help to make it a reality, let me know !

**Comment by mwilliamson** [comment]
Hmm, I'm not sure this is the right approach -- we probably want to store the actual values for the shadow and highlight so that they can be used (e.g. by matchers or by document transforms (see #292)). I'm going to close this for now, so if anybody wants to continue the discussion, please open an issue with a minimal example document, the expected HTML and the actual HTML.

**Pull request closed without merging**
