### PR TITLE
Minor fix for when attributes is not defined.

### PR DESCRIPTION
**Pull request by sfinktah**
```
/usr/local/lib/node_modules/mammoth/node_modules/bluebird/js/main/async.js:95
                throw res.e;
                         ^
TypeError: Cannot read property 'attributes' of undefined
    at BodyReader.xmlElementReaders.w:pPr (/usr/local/lib/node_modules/mammoth/lib/docx/body-reader.js:114:41)
    at readXmlElement (/usr/local/lib/node_modules/mammoth/lib/docx/body-reader.js:26:24)
    at Array.map (native)
    at readXmlElements (/usr/local/lib/node_modules/mammoth/lib/docx/body-reader.js:18:32)
    at BodyReader.xmlElementReaders.w:p (/usr/local/lib/node_modules/mammoth/lib/docx/body-reader.js:83:20)
    at readXmlElement (/usr/local/lib/node_modules/mammoth/lib/docx/body-reader.js:26:24)
    at Array.map (native)
    at Object.readXmlElements (/usr/local/lib/node_modules/mammoth/lib/docx/body-reader.js:18:32)
    at Object.convertXmlToDocument (/usr/local/lib/node_modules/mammoth/lib/docx/document-xml-reader.js:13:33)
    at /usr/local/lib/node_modules/mammoth/lib/docx/docx-reader.js:59:31
    at Result.flatMap (/usr/local/lib/node_modules/mammoth/lib/results.js:18:22)
```

### CODE REVIEW

**Comment by mwilliamson** [comment]
Thanks for the pull request. Do you have an example of a document where this is an issue?

**Comment by sfinktah** [comment]
http://www.legislation.vic.gov.au/domino/Web_Notes/LDMS/LTObject_Store/ltobjst9.nsf/DDE300B846EED9C7CA257616000A3571/80D9582B99595A86CA257E67001AAF38/$FILE/04-56a049A.docx

**Comment by mwilliamson** [comment]
Thanks for the example. Looking at the source document, it seems as if the correct behaviour (in the absence of the numId and level elements) is to ignore the numbering properties together. Does that match up to your expectations?

In terms of the code: any changes to Mammoth should be accompanied by tests that cover the behaviour. Would you rather make the changes yourself, or for me to do it?

**Comment by mwilliamson** [comment]
This should be fixed in 0.3.24, which I've just uploaded to npm. Thanks again for the report.

**Pull request closed without merging**
