### PR TITLE
feat(numbering): add numbering id to ast node

### LINKED ISSUE #267: Retain numbering id in list paragraphs
Assume you have a document with 2 level 0 ordered lists:

```
1. one
2. two
Something else
3. three
Something else
1. one
2. two
```

the numbering information provided in the AST node does not contain the information about the numbering, so it's not possible to continue the first list after the non-list paragraph.

```
document[8]
├─0 paragraph[1]
│   │ styleId: "ListParagraph"
│   │ numbering: {"isOrdered":true,"level":"0"}
│   └─0 run[1]
│       └─0 text "One"
├─1 paragraph[1]
│   │ styleId: "ListParagraph"
│   │ numbering: {"isOrdered":true,"level":"0"}
│   └─0 run[1]
│       └─0 text "Two"
├─2 paragraph[1]
│   │ styleId: "Normal"
│   └─0 run[1]
│       └─0 text "Something else"
├─3 paragraph[1]
│   │ styleId: "ListParagraph"
│   │ numbering: {"isOrdered":true,"level":"0"}
│   └─0 run[1]
│       └─0 text "Three"
├─4 paragraph[1]
│   └─0 run[1]
│       └─0 text "Something else"
├─5 paragraph[1]
│   │ styleId: "ListParagraph"
│   │ numbering: {"isOrdered":true,"level":"0"}
│   └─0 run[1]
│       └─0 text "One"
├─6 paragraph[1]
│   │ styleId: "ListParagraph"
│   │ numbering: {"isOrdered":true,"level":"0"}
│   └─0 run[1]
│       └─0 text " Two"
└─7 paragraph[0]
```

If the `numId` would be added to the `numbering` information, it would be possible to detect the continuation.

```
document[8]
├─0 paragraph[1]
│   │ styleId: "ListParagraph"
│   │ numbering: {"isOrdered":true,"level":"0","numId":"1"}
│   └─0 run[1]
│       └─0 text "One"
├─1 paragraph[1]
│   │ styleId: "ListParagraph"
│   │ numbering: {"isOrdered":true,"level":"0","numId":"1"}
│   └─0 run[1]
│       └─0 text "Two"
├─2 paragraph[1]
│   │ styleId: "Normal"
│   └─0 run[1]
│       └─0 text "Something else"
├─3 paragraph[1]
│   │ styleId: "ListParagraph"
│   │ numbering: {"isOrdered":true,"level":"0","numId":"1"}
│   └─0 run[1]
│       └─0 text "Three"
├─4 paragraph[1]
│   └─0 run[1]
│       └─0 text "Something else"
├─5 paragraph[1]
│   │ styleId: "ListParagraph"
│   │ numbering: {"isOrdered":true,"level":"0","numId":"4"}      <<========
│   └─0 run[1]
│       └─0 text "One"
├─6 paragraph[1]
│   │ styleId: "ListParagraph"
│   │ numbering: {"isOrdered":true,"level":"0","numId":"4"}
│   └─0 run[1]
│       └─0 text " Two"
└─7 paragraph[0]
```

```
diff --git a/lib/docx/numbering-xml.js b/lib/docx/numbering-xml.js
index 64c4210..a68fbf4 100644
--- a/lib/docx/numbering-xml.js
+++ b/lib/docx/numbering-xml.js
@@ -15,13 +15,16 @@ function Numbering(nums, abstractNums, styles) {
         }),
         "paragraphStyleId"
     );

     function findLevel(numId, level) {
         var num = nums[numId];
         if (num) {
             var abstractNum = abstractNums[num.abstractNumId];
             if (abstractNum.numStyleLink == null) {
-                return abstractNums[num.abstractNumId].levels[level];
+                var lvl = abstractNums[num.abstractNumId].levels[level];
+                return Object.assign({numId: numId}, lvl);
             } else {
                 var style = styles.findNumberingStyleById(abstractNum.numStyleLink);
                 return findLevel(style.numId, level);
```

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #267

(also updates the version of the `temp` dependency, which caused errors with node14)

### CODE REVIEW

**Comment by tripodsan** [comment]
Hi @mwilliamson is this project still active?

**Comment by tripodsan** [comment]
Hi @mwilliamson is this project still active?

**Comment by tripodsan** [comment]
Hi @mwilliamson is this project still active?

**Comment by mwilliamson** [comment]
> Hi @mwilliamson is this project still active?

Yes.

**Comment by mwilliamson** [comment]
Unless I've misunderstood, this doesn't change the outputted HTML, so presumably this is for use in document transforms? Or something else?

**Comment by tripodsan** [comment]
> Unless I've misunderstood, this doesn't change the outputted HTML, so presumably this is for use in document transforms? Or something else?

yes. we could alter the HTML output as well by using the [start](https://www.w3schools.com/Tags/att_ol_start.asp) attribute. for out use-case, having this information available in the document structure is sufficient. let me know, if I should also propagate this to the HTML output.

**Comment by mwilliamson** [comment]
If the goal is to set the `start` attribute, it sounds like that should be in this set of changes. Having some example documents, finding the relevant part of the spec (not that Word always follows the spec) and seeing what other applications (e.g. LibreOffice) do would be useful.

**Comment by mwilliamson** [comment]
Just to be clear: I'd suggest pulling together that information before making the changes, which might (or might not!) be easier for me to do (since I also have to make the changes in the other implementations of Mammoth).

**Comment by tripodsan** [comment]
as I said, adding the `numbering id` to the AST node is enough for most cases, as you can see 3 other users in #267 said, they need/want this fix. 

having a correct counting for HTML is IMO better suited in another PR, since it varies a lot of the use case (as you need to manage the counters for each numbering etc).

**Comment by mwilliamson** [comment]
I'm reluctant to accept a change where I haven't seen how it would be used to change the outputted HTML, so I'm closing this pull request. If anyone wants to continue the discussion, please do so on #267.

**Pull request closed without merging**
