### PR TITLE
document xml reader can now parse anchor links

### PR DESCRIPTION
**Pull request by alubbe**
see https://github.com/mwilliamson/mammoth.js/issues/35
solves the first part.

I am submitting this as a separate PR because Sublime deleted a lot of whitespace and the diff just kept getting crazier :D

This commit is the interesting one: https://github.com/alubbe/mammoth.js/commit/0a768e97f77cb0e482794a71c89d3ae293489daf

### CODE REVIEW

**Comment by mwilliamson** [comment]
Thanks for the pull request! I wonder if it would be better to store the internal anchors as a separate property, such as `anchor`, rather than `href`? That way, we don't need to parse `href` to differentiate between links to pages on the Internet, and internal anchors.

**Comment by alubbe** [comment]
do you mean the anchors/bookmarks that at the "receiving" end of the link or of the actual link itself? 

In HTML internal anchors set using href and the ```#``` prefix, so I would go for emulating that.

**Comment by alubbe** [comment]
With regards to the "receiving" end of the link, i. e., the bookmarks, could you give me another pointer?

I see that they need to be removed here
```js
var ignoreElements = {
    "w:bookmarkStart": true,
    "w:bookmarkEnd": true,
...
```
Do I then create a new key in ```xmlElementReaders```? If so, I haven't fully understood what these functions take in and what they return. These bookmarks are very simple:
```<w:bookmarkStart w:id="1" w:name="_Main_Heading"/>``` maps to ```<span id="_Main_Heading">``` and ```<w:bookmarkEnd/>``` maps to ```</span>```.

If you point me in the right direction, I'll take another swing at it!

**Comment by mwilliamson** [comment]
I mean that rather than having:

```
                var href;

                if (relationshipId) {
                    href = relationships[relationshipId].target;
                    return new documents.Hyperlink(children, {href: href});
                } else if (anchor) {
                    href = "#" + anchor;
                    return new documents.Hyperlink(children, {href: href});
                } else {
                    return children;
                }
```

have:

```
                if (relationshipId) {
                    var href = relationships[relationshipId].target;
                    return new documents.Hyperlink(children, {href: href});
                } else if (anchor) {
                    return new documents.Hyperlink(children, {anchor: anchor});
                } else {
                    return children;
                }
```

As for why: `href` and `anchor` represent different concepts, so I think they should be stored separately. To give an example of why this is useful: we probably want to rewrite anchors (for instance, to ensure their IDs are unique) while we don't want to do so for external links. If they're stored in the same property, we need to check the first character of `href` each time, since we've lost the (explicit) fact that it's an internal anchor. By storing it in a separate property, we keep this useful fact hanging around so we can use it later without having to parse text.

**Comment by mwilliamson** [comment]
To answer your second question: Mammoth converts documents in two steps. The first is to read the XML document and turn it into a tree of document elements (similar to the DOM in a browser). This is what happens in `document-xml-reader.js`, so you'd probably want to convert `w:bookmarkStart` and `w:bookmarkEnd` into a single document element representing a bookmark.

Having done that, `document-to-html.js` can then convert that tree of documents into HTML.

**Comment by alubbe** [comment]
okay I see your point about separating out the anchors - thing is, the information gets lost somewhere in the process. I feel like there is somewhere in the code that stops all hyperlinks with empty href from being cascaded any further. What am I missing (see commit)?

**Comment by mwilliamson** [comment]
Hmm, from a quick glance, what you've written seems sensible. Perhaps try adding appropriate tests for the code you've modified to check it's working as you expect?

One thing I did spot: the usage of the conditional operator to generate `href` doesn't seem quite right:

```javascript
            var href = element.href ||
                       element.anchor ? "#" + element.anchor : undefined;
```

I think that the precedence is something like:

```javascript
            var href = (element.href ||
                       element.anchor) ? "#" + element.anchor : undefined;
```

Which doesn't seem like what you intended. I think you want something more like:

```javascript
            var href = element.anchor ? "#" + element.anchor : element.href;
```

**Comment by alubbe** [comment]
okay I am starting to figure out how this flows - it now works

**Comment by alubbe** [comment]
yes I prefer that shorter version that you suggest - updated

**Comment by alubbe** [comment]
ok I am making good headway with implementing the bookmarks.

In doing so, there is one fundamental decision to make: will bookmarks ever have children?
All the occurrences I could find closed immediately like this:
```xml
<w:bookmarkStart w:id="1" w:name="_Peter"/>
<w:bookmarkEnd w:id="1"/>
```
Is there some documentation or do you know the answer to this?

If my hunch is correct, I would keep ignoring ```w:bookmarkEnd``` and parse ```w:bookmarkStart``` into a self-closing ```span```.

**Comment by mwilliamson** [comment]
There is indeed some documentation which suggests that bookmarks can have children: https://msdn.microsoft.com/en-us/library/documentformat.openxml.wordprocessing.bookmarkstart%28v=office.14%29.aspx

**Comment by alubbe** [comment]
Ok so how about 
```<w:bookmarkStart w:id="1" w:name="_Peter"/>```
becomes
```<span id="_Peter" data-bookmarkStartId="1"></span>```
and
```<w:bookmarkEnd w:id="1"/>```
becomes
```<span data-bookmarkEndId="1"></span>```


Lastly, there is one type of bookmark that is contained in every single word document ( a simple pointer at the last edit of the document) that you have previously considered unnecessary for the HTML output:
```xml
<w:bookmarkStart w:id="0" w:name="_GoBack"/>
<w:bookmarkEnd w:id="0"/>
```
There are two ways of ignoring this tag:
1) Completely ignore it at the level of document-xml-reader. This is the current solution and prevents it from showing up in the AST
2) Permit it into the AST but ignore it at the level of document-to-html
If we are being purist, 2) should be favoured, but it breaks 22 of your old tests (because the AST is extended). Also, I am not sure what value it adds to the AST keeping in mind that the bookmark's position always jumps around with each new save and that the value of a "feature" of jumping to the user's last docx edit within an HTML document seems limited.

Let me know which you prefer.

**Comment by alubbe** [comment]
It's done, I went the purist way - let me know what you think!

**Comment by mwilliamson** [comment]
Thanks again for taking a look at this!

> It's done, I went the purist way - let me know what you think!

I'm not quite sure what you mean by the purist way. The document AST doesn't need to match the structure of the docx: in fact there are several places where it intentionally doesn't in order to simplify the overall structure. Thinking a bit more about it, does storing the bookmark end ever help us? We could probably get away with just storing the bookmark start.

Similarly, we could probably strip out any bookmarks we don't care about during the parsing phase. Rather than hard-coding `_GoBack` as a special-case, we could just generate a list of referenced bookmark names beforehand, and only include books if they're in that list.

I also noticed that the generated `span` elements have `data-` attributes on them. How were you planning on using those `data-` attributes?

**Comment by alubbe** [comment]
bookmarkEnd could be useful if your bookmark is used in and around tables, where it can mark columns that then receive a special markup (just like ```<span class="...">``` does). https://msdn.microsoft.com/en-us/library/documentformat.openxml.wordprocessing.bookmarkstart%28v=office.14%29.aspx#remarksToggle

if we choose to remove bookmarkEnd, we can also remove the "id" property from bookmarkStart, as its only value lies in connecting a bookmarkEnd to its bookmarkStart. That's also the reason that I pass it into that ```data-``` attribute, so that they can be matched in the final output.

I don't follow your suggestion on generating a list of referenced bookmark names, could you elaborate?

**Comment by mwilliamson** [comment]
> bookmarkEnd could be useful if your bookmark is used in and around tables, where it can mark columns that then receive a special markup (just like <span class="..."> does). https://msdn.microsoft.com/en-us/library/documentformat.openxml.wordprocessing.bookmarkstart%28v=office.14%29.aspx#remarksToggle

I'm not quite sure I understand -- could you give an example of the HTML you'd generate (that would be different to if you didn't have the bookmarkEnd element)?

> I don't follow your suggestion on generating a list of referenced bookmark names, could you elaborate?

Before converting the XML document into an AST, scan the entire tree for bookmark references. Each time you find a bookmark reference, store the name of the bookmark being referenced. When actually generating the AST, ignore any bookmarks that wasn't mentioned by a bookmark reference.

**Comment by alubbe** [comment]
Well, we could merge both of our approaches if, instead of converting bookmarkStart bookmarkEnd to this
```html
<span id =.. data-bookmark-start=...></span>
...
<span data-bookmark-end=..></span>
```
we try to convert both into this statement
```html
<span id=..>
.......
</span>
```
This is what I had in mind originally, but there is one big problem: there is no guarantee that the bookmarkEnd appears at a place that would allow a semantically correct ```</span>```. bookmarkStart It is literally meant to be a "start"-point and bookmarkEnd an "end"-pont as interpreted by someone writing a word document (possibly involving tables). 

To give you an example, here is the example by Microsoft
```xml
<w:tbl>
    ...
    <w:tr>
        <w:tc>
            <w:bookMarkStart w:colFirst="0" w:colLast="1" w:id="0" w:name="table"/>
            <w:p/>
        </w:tc>
        <w:tc>
            <w:p/>
        </w:tc>
        <w:tc>
            <w:p/>
        </w:tc>
    </w:tr>
    <w:tr>
        <w:tc>
            <w:p/>
        </w:tc>
        <w:tc>
            <w:p/>
        </w:tc>
        <w:tc>
            <w:p/>
        </w:tc>
        <w:bookmarkEnd w:id="0" />
    </w:tr>
    <w:tr>
        <w:tc>
            <w:p/>
        </w:tc>
        <w:tc>
            <w:p/>
        </w:tc>
        <w:tc>
            <w:p/>
        </w:tc>
    </w:tr>
</w:tbl>
```
I don't see a great way of opening a ```<span>``` at the Start and then closing ```</span>``` at the End. Thus I chose to go the route of marking the Start and End with ```<span ...></span>```, exactly as Microsoft does. As a consequence, we must save and pass on the bookmarkId, otherwise the two markers cannot be matched.

**Comment by alubbe** [comment]
Regarding your comment to the bookmark references, it makes sense to me now. 
But I do disagree with this approach. I can see a use case where I set a bookmark in the word document which isn't used by an anchor link yet but that is important to the HTML dev for referencing it in the DOM, to be used for CSS or JS transformations. I think it removes information that may have been there on purpose.

From my research, _GoBack is the only reference of its kind. I do see your point of hard-coding strings, so instead I would propose to use an array of black-listed strings as part of the options object with the default value being ```["_GoBack"]```. This way, users can add more references  to be ignored or even whitelist _GoBack, if needed.

**Comment by mwilliamson** [comment]
I think we're disagreeing more on what use cases to support rather than actual implementation. The use case I have in mind is making internal links (i.e. links from one part of the document to another) work, for which I don't think having the bookmark end is necessary.

Are there other use cases that I've missed that you need support for?

**Comment by alubbe** [comment]
No, there are no other use cases that I need at the moment. That is why I referred to this as the "purist way", i. e., preserving all information. Do you want to drop bookmarkEnd altogether or just not print it out into HTML?

Also, what's your take on black-listing specific bookmarks instead of pre-scanning anchor links?

**Comment by mwilliamson** [comment]
In that case, I'd say get rid of bookmark end altogether, and only include bookmarks required for internal links on the basis that it's easier to add functionality later than to remove existing functionality.

**Comment by alubbe** [comment]
I'll gladly do that :)

What about the other issue of ```GoBack``` - could you please me give your input? https://github.com/mwilliamson/mammoth.js/pull/37#issuecomment-72190586

**Comment by mwilliamson** [comment]
Sorry, when I said to only include bookmarks for internal links, I meant that only bookmarks that are referenced in the document should be included. Thanks!

**Comment by alubbe** [comment]
Yes, I understood that, but I can see a use case where I set a bookmark in the word document which isn't used by an anchor link but that is important to the HTML dev for referencing it in the DOM, to be used for CSS or JS transformations. I think it removes information that may have been there on purpose.

From my research, _GoBack is the only reference of its kind. I do see your point of disliking hard-coded strings, so instead I would propose to use an array of black-listed strings as part of the options object with the default value being ["_GoBack"]. This way, users can add more references to be ignored or even whitelist _GoBack, if needed.

**Comment by mwilliamson** [comment]
I can see that as a potential use case, but I'd avoid supporting it until somebody actually says they want it.

**Comment by alubbe** [comment]
Okay so now all (except one) of these features have been put into code - the diff is best viewed here: https://github.com/alubbe/mammoth.js/compare/47bfdff...master

The only thing that needs to be added is to scan the document beforehand, create an array of white-listed bookmarks and replace the if statement that currently checks for "_GoBack" with an ```Array.indexOf```

While I have several ideas of how to implement this scan, I am not sure where in the code base you'd feel most comfortable to place it. Can I leave this implementation to you?

**Comment by mwilliamson** [comment]
I've merged in your changes, except I squashed and got rid of the whitespace changes. 0.3.17 is now on npm and contains your changes. Thanks for the contribution!

**Pull request closed without merging**
