### PR TITLE
Added basic parsing of document headers and footers

### PR DESCRIPTION
**Pull request by moo2u2**
Based on[ PR66 for the python version](https://github.com/mwilliamson/python-mammoth/pull/66) I have added basic support for document headers + footers.

`--include-headers-footers`: If enabled, includes header text at start of output, and appends footer text to end.

### CODE REVIEW

**Comment by circlehddev** [comment]
Any idea when this can be merged? Much needed feature.

**Comment by mwilliamson** [comment]
I'm afraid I'm not currently accepting pull requests.

**Comment by moo2u2** [comment]
@JiaYiChow that's exactly what this PR is... you can view my updated fork at https://github.com/moo2u2/mammoth.js/tree/master (link at the top where it says "from moo2u2:master")

**Comment by JiaYiChow** [comment]
> @JiaYiChow that's exactly what this PR is... you can view my updated fork at https://github.com/moo2u2/mammoth.js/tree/master (link at the top of this PR where it says "from moo2u2:master")

@moo2u2  sorry i meant to say would it be possible to publish a separate npm package based on that pr

**Pull request closed without merging**
