### PR TITLE
Adds translation support for horizontal rules

### PR DESCRIPTION
**Pull request by connordeckers**
This change allows detection of Horizontal Rules, and can auto-translate them to the relevant `<hr />` html analogue.

### CODE REVIEW

**Comment by connordeckers** [comment]
Will fix failing tests (my first PR, apologies).

**Comment by mwilliamson** [comment]
There seems to be a lot of unrelated changes in the diff, which makes this hard to review. Could you tidy up the patch to only contain relevant changes?

Also, could you provide an example document?

**Comment by connordeckers** [comment]
No worries. Apologies, this is my first PR so I'm figuring it out as I go 😅  
I believe the changes are predominantly whitespace, so I'll see if I can reset those changes (Prettier decided to change everything).

Can I clarify, regarding the example document, do you mean an example Word document and converted HTML output?

**Comment by mwilliamson** [comment]
> Can I clarify, regarding the example document, do you mean an example Word document and converted HTML output?

Yes, exactly.

**Comment by mwilliamson** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
