### PR TITLE
Add extract method which exposes a read document

### PR DESCRIPTION
**Pull request by stoogoff**
Mammoth.js is superb but I need to convert docx to Markdown rather than HTML. This patch exposes the read docx file allowing consuming code to create its own custom DocumentConverter or handle the docx document structure in any way it needs to.

For my immediate use case it would probably be simpler to allow a custom writer to be passed as an option to the convertToHtml function.

### CODE REVIEW

**Comment by mwilliamson** [comment]
Hello! Thanks for the pull request. In general, I try not to expose the internals of Mammoth so that they can be changed without breaking other people's code. (Admittedly, I do expose the document by providing document transforms, but it's something that few people use, and `mammoth.transforms.paragraph` helps by abstracting over some of the details. I do slightly regret making that available!)

Having said that, I can see why exposing the AST would be useful. Would adding support for Markdown directly to Mammoth be an option? That way, we don't encourage people to rely on the AST (which we might want to change in the future), but still support your use case.

**Comment by stoogoff** [comment]
I see what you mean about exposing the AST, it's something that you need to
know isn't going to change too much or too often. Adding direct support for
Markdown to Mammoth would suit me perfectly! I think this would be simple
enough to do with either a MarkdownGenerator or MarkdownWriter. I should
have some time tomorrow to take a look at that.

**Comment by stoogoff** [comment]
I've committed the following: https://github.com/stoogoff/mammoth.js/commit/db0c6dda95cad470dcf4c6272885683849833aae

This adds a markdown-writer to Mammoth and changes html-generator so it can switch between a markdown-writer and an html-writer based on a config option. Usage would be:

```javascript
mammoth.convertToHtml(options, { markdown: true }).then(function(result){
    var value = result.value; // The generated Markdown
    var messages = result.messages; // Any messages, such as warnings during conversion

    console.log(value);
    console.log(messages)
});
```
It might be better to add a `convertToMarkdown` method instead or possibly rename `convertToHtml` to `convertTo` and keep the Markdown config option, but I'll leave that to your judgement. There are some slight semantic issues now (html-generator isn't *really* an html-generator any more, document-to-html isn't just *to-html* etc), I don't know how much that sort of thing annoys you!

If you're happy with this I'll add test cases and update the README.

**Comment by mwilliamson** [comment]
I haven't a had a chance to have a proper look, but from a glance this looks pretty good to me! Off the top of my head, I might tweak the way that `HtmlGenerator` is constructed so that it gets passed a writer, rather than having the generator create a writer itself, but I'd need to actually play with the code if that turns out any better or not.

**Comment by mwilliamson** [comment]
This generally looks good to me: there are a couple of minor stylistic tweaks I think I want to make, but it's nothing significant, so I'd suggest that you add your test cases and whatever else you think is necessary, and then I'll merge in it.

**Comment by stoogoff** [comment]
Excellent, I'll get the test cases added today. I think having a writer passed to `HtmlGenerator` would be a better idea as it would allow you to expose a small but useful API for writing other document formats while still keeping the AST internal to Mammoth.

**Comment by mwilliamson** [comment]
I've added markdown support to `master`, along with a couple of tweaks. Thanks for doing the hard work!

**Pull request closed without merging**
