### PR TITLE
Added extracting the date of the comment reference

### PR DESCRIPTION
**Pull request by serjant**

### CODE REVIEW

**Comment by mwilliamson** [comment]
Thanks for the pull request. Unfortunately, I'd be reluctant to include `data-` attributes since it introduces noise into the generated HTML for a specific use-case.

**Comment by serjant** [comment]
That is partially true, but frankly speaking, the library uses the <comment> tag as output for the comment references in DOM which introduces the same noise.

**Comment by mwilliamson** [comment]
I'm afraid I don't follow. At the moment, the generated HTML has a visible effect in the resulting document without any further processing or enhancement, whether that's the body of the comment itself or the linking between the reference and the comment. The same isn't true of the `data-` attributes: by default, they have no effect.

**Comment by serjant** [comment]
Yeah, it is likely more specific for my needs and maybe for other who will make the HTML further processing of the document after the mammoth output. So I will close the pull request.

**Pull request closed without merging**
