### PR TITLE
Ignore v:imagedata elements without relationship ID with warning

### PR DESCRIPTION
**Pull request by liamzh**
This PR prevents from crash when `mammoth.js` encounters an empty `element.attributes['r:id']`.

### CODE REVIEW

**Comment by mwilliamson** [comment]
Thanks for the pull request. It looks like the build is currently
failing though. Also, could you add a minimal test case to cover this
change?

**Comment by mwilliamson** [comment]
Thanks for the changes. For the test case, could it instead test the body reader directly (i.e. be a test in `body-reader.tests.js`)? Doing so should hopefully make the intent of the test (and intended behaviour of the code) clearer.

**Comment by liamzh** [comment]
@mwilliamson ok, I didn't notice `body-reader.test.js` just now. :)

**Comment by mwilliamson** [comment]
Sorry, I don't think I was very clear: when I said putting the test in
body-reader.test.js, I also meant writing the test in the same style as
the other tests in that suite. Specifically, rather than reading an
entire document (which causes many parts of Mammoth to be tested, not
just the body reader), you can just pass in the XML AST of the elements
you want to read. That way, the behaviour that we're interested in can
be tested in isolation.

**Comment by mwilliamson** [comment]
Thanks for the pull request!

**Pull request merged**
