### PR TITLE
xml style map support

### PR DESCRIPTION
**Pull request by satchelspencer**
possible solution for implementing functionality for xml properties that are not currently included

### CODE REVIEW

**Comment by mwilliamson** [comment]
Thanks for the pull request. I'm a bit wary of exposing the underlying XML structure since I view that as internal state that might change between any version. (The same is roughly true for the internal document structure: that'll be documented in 1.0.) Is there a reason why document transforms don't do the job, as described in #57? If absolutely necessary, the underlying XML node could be attached to the document element, and then a document transform used to add the styles, which feels neater to me since it doesn't really require adding anything to the API while not making things any harder. I'd much rather find a way of solving whatever your use case is without exposing the XML structure though.

**Comment by satchelspencer** [comment]
As you mentioned in #57 
> I think the only thing stopping you from doing so is that the docx reader ignores some of the properties you want to use, such as colour and size

A couple example use cases include detecting highlights (see added test from pull request), recognizing size to find headers, indented paragraphs etc. I do like the idea of attaching the underlying XML to the document element and making it available during transform. Allowing direct access to the XML vastly increases mammoth's usefulness, and leaves the implementation of non-standard features up to the end user. I do understand your hesitation in exposing an underlying structure that isn't standardized and may change. Though documentTransform already exposes this to some degree, and the XML of any one document is fixed.

**Comment by mwilliamson** [comment]
> and the XML of any one document is fixed.

To clarify: my concern isn't about exposing the XML structure itself, but the mechanism that Mammoth uses to read it. In words, exposing the API of the XML nodes.

**Comment by satchelspencer** [comment]
Understood, the way the xml is represented internally may change, not the xml itself. Would you be comfortable adopting a fixed api (from an existing standard) **only** for the xml that would be available in transformDocument?

**Comment by mwilliamson** [comment]
What existing standard were you thinking of?

**Comment by mwilliamson** [comment]
To expand: the answer is possibly. I think adding the XML nodes to the document elements adds some complexity to the codebase, but if it can be done reasonably simply, then I don't have a problem with it so long as it's hidden behind a flag.

If there is some existing standard for representing XML in JavaScript, then it's worth considering using that throughout rather than having to convert each time an element is processed and the corresponding flag is on.

**Comment by satchelspencer** [comment]
[here](http://wiki.open311.org/JSON_and_XML_Conversion/) is a reasonably complete list of appraoches. sax was a good choice for your purposes, and could be used, though [xml2js](https://github.com/Leonidas-from-XIV/node-xml2js) is very popular and can produce a standardized output (similar by default to the [badgerfish convention](http://www.sklar.com/badgerfish/)). It can also be used as an XML generator. 

I agree that it would add some complexity to the codebase, but it would be an advantage to have a standardized internal representation of the xml going forward.

**Comment by mwilliamson** [comment]
I'm not sure SAX is particularly appropriate here: presumably we want to expose an already-parsed object, rather than requiring the user to implement SAX-style callbacks? I'd be keener to choose a format that doesn't try to convert the XML to JSON since, as the different conventions show, there's no single way that is immediately obvious. In other words, I'd be more in favour of a structure that allows interrogation of the XML structure, such as the DOM, rather than trying to convert it to JSON.

**Comment by satchelspencer** [comment]
I like that, allowing DOM-like access to the xml would be more helpful for the end user regardless. Is something like [xmldom](https://github.com/jindw/xmldom) what you're thinking of? Would you rather use that only when the flag is enabled, or as a replacement for your current internal structure as well? I haven't fully considered what kind of overhead that would add over your current implementation.

**Comment by mwilliamson** [comment]
If there was a representation that's as convenient to use as the existing implementation, then I'd happily replace it. I would suspect that I didn't find the DOM particularly convenient, since I'd expect it to have been around when I first wrote mammoth.js, and would have been aware of it, but evidently didn't pick it.

I haven't really looked around for a replacement though since the current implementation works very nicely.

**Comment by satchelspencer** [comment]
Sounds reasonable, I'll play around with it for my own needs. If I arrive at a method of exposing the xml that fits well within your current implementation, I'll let you know. Thanks for all info and ideas, cheers.

**Comment by sheldonnbbaker** [comment]
@satchelspencer Did you manage to implement that? I believe I'm in need of something similar (extracting highlighted text from some .doc files).

**Pull request closed without merging**
